# Site settings
title: Ege EBYS+
author: Bekir Uzun
subtitle: 
email: # example@example.com
description: Ege Üniversitesi EBYS için tasarım modülü
baseurl: "" # the subpath of your site, e.g. /blog
url: ""

# Plugins
plugins:
  - jekyll-sitemap

exclude:
  - node_modules
  - bkp

permalink: /:title

# Social settings
500px_url:
facebook_url: 
github_url: https://github.com/BekirUzun/EgeEBYSPlus
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge

  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'
